# Site settings
name: My Blogs
email: caizerun@.com
author: Cafory
url: http://cafory.github.io
resume_site: http://cafory.github.io
github: https://github.com/cafory/
baseurl: ''
description: Actually, less is more!
meta_description: chongchongchong
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cafory

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

