# Site settings
name: My Blogs
email: caizerun@.com
author: Cafory
url: http://cafory.github.io
resume_site: http://cafory.github.io
github: https://github.com/cafory/
baseurl: ''
description: 士不可以不弘毅，任重而道远。
meta_description: Use it or lose it.
motto: Use it or lose it.
banner: 壁立千仞，无欲则刚。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cafory

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

